/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package TokoBunga;

import TokoBunga.Transaksitokobunga;
import java.text.*;
import java.util.*;
import javax.persistence.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Huawei
 */
public class DeleteDialog2 extends java.awt.Dialog {

    private EntityManagerFactory emf;
    private EntityManager em;

    private String idTransaksiLama, idBungaLama, namaPelangganLama;
    private Date tanggalLama;
    private int jumlahLama, totalHargaLama;

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("PertemuanKesebelasPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public DeleteDialog2(java.awt.Frame parent, boolean modal,
            String idTransaksi, String idBunga, String namaPelanggan,
            Date tanggal, int jumlah, int totalHarga) {

        super(parent, modal);
        initComponents();
        connect();

        this.idTransaksiLama = idTransaksi;
        this.idBungaLama = idBunga;
        this.namaPelangganLama = namaPelanggan;
        this.tanggalLama = tanggal;
        this.jumlahLama = jumlah;
        this.totalHargaLama = totalHarga;

        TxtIdTransaksi.setText(idTransaksi);
        TxtIdBunga.setText(idBunga);
        TxtNamaPelanggan.setText(namaPelanggan);
        DtcTanggalTransaksi.setDate(tanggal);
        SpJumlahPesanan.setValue(jumlah);
        TxtTotalHarga.setText(String.valueOf(totalHarga));

        TxtIdTransaksi.setEditable(false);
        TxtIdBunga.setEditable(false);
        TxtNamaPelanggan.setEditable(false);
        DtcTanggalTransaksi.setEnabled(false);
        SpJumlahPesanan.setEnabled(false);
        TxtTotalHarga.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnTidak2 = new javax.swing.JButton();
        BtnYa2 = new javax.swing.JButton();
        TxtIdTransaksi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtIdBunga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtNamaPelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DtcTanggalTransaksi = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        SpJumlahPesanan = new com.toedter.components.JSpinField();
        jLabel7 = new javax.swing.JLabel();
        TxtTotalHarga = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnTidak2.setBackground(new java.awt.Color(255, 102, 204));
        BtnTidak2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnTidak2.setForeground(new java.awt.Color(255, 255, 255));
        BtnTidak2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnTidak2.setLabel("Tidak");
        BtnTidak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTidak2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnTidak2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 100, 30));

        BtnYa2.setBackground(new java.awt.Color(255, 102, 204));
        BtnYa2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnYa2.setForeground(new java.awt.Color(255, 255, 255));
        BtnYa2.setText("Ya");
        BtnYa2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnYa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnYa2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnYa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 100, 30));

        TxtIdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(TxtIdTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 110, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("ID Transaksi");
        jLabel2.setAutoscrolls(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 87, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("ID Bunga");
        jLabel3.setAutoscrolls(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        TxtIdBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdBungaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtIdBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 110, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Nama Pelanggan");
        jLabel4.setAutoscrolls(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        TxtNamaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaPelangganActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Tanggal Transaksi");
        jLabel5.setAutoscrolls(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel1.add(DtcTanggalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Jumlah Pesanan");
        jLabel6.setAutoscrolls(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, -1));
        jPanel1.add(SpJumlahPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 110, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("Total Harga");
        jLabel7.setAutoscrolls(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, -1));

        TxtTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalHargaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void BtnTidak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTidak2ActionPerformed
        dispose();
    }//GEN-LAST:event_BtnTidak2ActionPerformed

    private void BtnYa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnYa2ActionPerformed
        int jumlah = (Integer) SpJumlahPesanan.getValue();
        
        if (TxtIdTransaksi.getText().equals("")
                || TxtIdBunga.getText().equals("")
                || TxtNamaPelanggan.getText().equals("")
                || DtcTanggalTransaksi.getDate() == null
                || jumlah == 0
                || TxtTotalHarga.getText().equals("")) {

            JOptionPane.showMessageDialog(null, "Isi semua data");

        } else {
            EntityManagerFactory emf = null;
            EntityManager em = null;

            try {
                emf = Persistence.createEntityManagerFactory("PertemuanKesebelasPU");
                em = emf.createEntityManager();

                String idTransaksi = TxtIdTransaksi.getText();

                em.getTransaction().begin();
                Transaksitokobunga trx = em.find(Transaksitokobunga.class, idTransaksiLama);

                if (trx == null) {
                    JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                } else {
                    em.remove(trx);
                    em.getTransaction().commit();
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                    dispose();
                }
            } catch (Exception e) {
                if (em != null && em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
            } finally {
                if (em != null) {
                    em.close();
                }
                if (emf != null) {
                    emf.close();
                }
            }
        }
    }//GEN-LAST:event_BtnYa2ActionPerformed

    private void TxtIdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdTransaksiActionPerformed

    private void TxtIdBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdBungaActionPerformed

    private void TxtNamaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaPelangganActionPerformed

    private void TxtTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalHargaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DeleteDialog2 dialog = new DeleteDialog2(new java.awt.Frame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnTidak2;
    private javax.swing.JButton BtnYa2;
    private com.toedter.calendar.JDateChooser DtcTanggalTransaksi;
    private com.toedter.components.JSpinField SpJumlahPesanan;
    private javax.swing.JTextField TxtIdBunga;
    private javax.swing.JTextField TxtIdTransaksi;
    private javax.swing.JTextField TxtNamaPelanggan;
    private javax.swing.JTextField TxtTotalHarga;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
