/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TokoBunga;

import static TokoBunga.Transaksitokobunga_.tanggal;
import java.io.*;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.filechooser.FileSystemView;
import javax.swing.table.*;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.util.JRLoader;
import javax.persistence.*;

/**
 *
 * @author Huawei
 */
public class TokoBunga extends javax.swing.JFrame {

    private EntityManagerFactory emf;
    private EntityManager em;

    String idBungaLama, namaBungaLama, kategoriBungaLama, deskripsiLama, hargaLama, stokLama, ukuranLama;

    public TokoBunga() {
        initComponents();
        connect();
        showTable1();
        showTable2();
    }

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("PertemuanKesebelasPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public void showTable1() {
        em.clear();
        EntityManager em = Persistence.createEntityManagerFactory("PertemuanKesebelasPU").createEntityManager();
        Query q = em.createNamedQuery("Tokobunga_1.findAll");
        List<Tokobunga_1> hasil = q.getResultList();

        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"ID Bunga", "Nama Bunga", "Kategori", "Deskripsi", "Harga", "Stok", "Ukuran"}, 0
        );
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (Tokobunga_1 t : hasil) {
            model.addRow(new Object[]{
                t.getIdbunga(),
                t.getNamabunga(),
                t.getKategoribunga(),
                t.getDeskripsiproduk(),
                t.getHarga(),
                t.getStok(),
                t.getUkuran()
            });
        }
        jTable1.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        jTable1.setModel(model);
        model.fireTableDataChanged();
        jTable1.revalidate();
        jTable1.repaint();
    }

    public void showTable2() {
        try {
            em.clear();
            EntityManager em = Persistence.createEntityManagerFactory("PertemuanKesebelasPU").createEntityManager();
            Query q = em.createNamedQuery("Transaksitokobunga.findAll");
            List<Transaksitokobunga> hasil = q.getResultList();

            tbmk = new DefaultTableModel(
                    new String[]{"ID Transaksi", "ID Bunga", "Nama Pelanggan", "Tanggal Transaksi", "Jumlah Pesanan", "Total Harga"}, 0
            );
            DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
            centerRenderer.setHorizontalAlignment(JLabel.CENTER);
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
            for (Transaksitokobunga data : hasil) {
                String tanggalFormatted = "";
                if (data.getTanggal() != null) {
                    tanggalFormatted = sdf.format(data.getTanggal());
                }
                Object[] baris = new Object[6];
                baris[0] = data.getIdtransaksi();
                baris[1] = data.getIdbunga() != null ? data.getIdbunga().getIdbunga() : "";
                baris[2] = data.getNamapelanggan();
                baris[3] = tanggalFormatted;
                baris[4] = data.getJumlah();
                baris[5] = data.getTotalharga();
                tbmk.addRow(baris);
            }

            jTable2.setModel(tbmk);
            jTable2.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tampil data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnExit = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        BtnUpload = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnInsert = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnCetak = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        BtnUpdate2 = new javax.swing.JButton();
        BtnInsert2 = new javax.swing.JButton();
        BtnDelete2 = new javax.swing.JButton();
        BtnCetak2 = new javax.swing.JButton();
        BtnUpload2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TokoBunga/Background.png"))); // NOI18N

        jTable3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Bunga", "Nama Bunga", "Kategori Bunga", "Deskripsi Produk", "Harga", "Stok Bunga", "Ukuran Buket"
            }
        ));
        jTable3.setMinimumSize(new java.awt.Dimension(450, 80));
        jTable3.setPreferredSize(new java.awt.Dimension(450, 80));
        jTable3.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jTable1MouseWheelMoved(evt);
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Data Pesanan toko Bunga ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 670, 50));

        BtnExit.setBackground(new java.awt.Color(204, 0, 0));
        BtnExit.setForeground(new java.awt.Color(255, 255, 255));
        BtnExit.setText("X");
        BtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(BtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        BtnUpload.setBackground(new java.awt.Color(255, 102, 204));
        BtnUpload.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnUpload.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpload.setText("Upload");
        BtnUpload.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnUpload.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUploadActionPerformed(evt);
            }
        });

        BtnDelete.setBackground(new java.awt.Color(255, 102, 204));
        BtnDelete.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelete.setText("Delete");
        BtnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnInsert.setBackground(new java.awt.Color(255, 102, 204));
        BtnInsert.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnInsert.setForeground(new java.awt.Color(255, 255, 255));
        BtnInsert.setText("Insert");
        BtnInsert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsertActionPerformed(evt);
            }
        });

        BtnUpdate.setBackground(new java.awt.Color(255, 102, 204));
        BtnUpdate.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate.setText("Update");
        BtnUpdate.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnCetak.setBackground(new java.awt.Color(255, 102, 204));
        BtnCetak.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnCetak.setForeground(new java.awt.Color(255, 255, 255));
        BtnCetak.setText("Print");
        BtnCetak.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetakActionPerformed(evt);
            }
        });

        jScrollPane3.setPreferredSize(new java.awt.Dimension(600, 300));

        jTable1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Bunga", "Nama Bunga", "Kategori Bunga", "Deskripsi Produk", "Harga", "Stok Bunga", "Ukuran Buket"
            }
        ));
        jTable1.setMinimumSize(new java.awt.Dimension(450, 80));
        jTable1.setPreferredSize(null);
        jTable1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jTable1MouseWheelMoved(evt);
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BtnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BtnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUpload, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        BtnDelete.getAccessibleContext().setAccessibleDescription("");
        BtnInsert.getAccessibleContext().setAccessibleDescription("");
        BtnUpdate.getAccessibleContext().setAccessibleDescription("");

        jTabbedPane2.addTab("Data Buket", jPanel1);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(600, 300));

        jTable2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "ID Bunga", "Nama Pelanggan", "Tanggal Transaksi", "Jumlah Pesanan", "Total Harga"
            }
        ));
        jTable2.setPreferredSize(null);
        jScrollPane2.setViewportView(jTable2);

        BtnUpdate2.setBackground(new java.awt.Color(255, 102, 204));
        BtnUpdate2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnUpdate2.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate2.setText("Update");
        BtnUpdate2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate2ActionPerformed(evt);
            }
        });

        BtnInsert2.setBackground(new java.awt.Color(255, 102, 204));
        BtnInsert2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnInsert2.setForeground(new java.awt.Color(255, 255, 255));
        BtnInsert2.setText("Insert");
        BtnInsert2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnInsert2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnInsert2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInsert2ActionPerformed(evt);
            }
        });

        BtnDelete2.setBackground(new java.awt.Color(255, 102, 204));
        BtnDelete2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnDelete2.setForeground(new java.awt.Color(255, 255, 255));
        BtnDelete2.setText("Delete");
        BtnDelete2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelete2ActionPerformed(evt);
            }
        });

        BtnCetak2.setBackground(new java.awt.Color(255, 102, 204));
        BtnCetak2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnCetak2.setForeground(new java.awt.Color(255, 255, 255));
        BtnCetak2.setText("Print");
        BtnCetak2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnCetak2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetak2ActionPerformed(evt);
            }
        });

        BtnUpload2.setBackground(new java.awt.Color(255, 102, 204));
        BtnUpload2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnUpload2.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpload2.setText("Upload");
        BtnUpload2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnUpload2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BtnUpload2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpload2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BtnInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BtnUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BtnDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BtnCetak2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BtnUpload2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnInsert2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCetak2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUpload2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Data Pesanan", jPanel2);

        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 710, 430));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TokoBunga/Background.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtnExitActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void jTable1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jTable1MouseWheelMoved

    }//GEN-LAST:event_jTable1MouseWheelMoved

    private void BtnUpload2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpload2ActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File filePilihan = jfc.getSelectedFile();
            System.out.println("File yang dipilih: " + filePilihan.getAbsolutePath());

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PertemuanKesebelasPU");
            EntityManager em = emf.createEntityManager();

            try (BufferedReader br = new BufferedReader(new FileReader(filePilihan))) {
                String baris;
                String pemisah = ";";

                em.getTransaction().begin();

                while ((baris = br.readLine()) != null) {
                    if (baris.trim().isEmpty()) {
                        continue;
                    }

                    String[] data = baris.split(pemisah);
                    if (data.length < 6) {
                        System.out.println("Baris tidak lengkap, dilewati: " + baris);
                        continue;
                    }

                    String idtransaksi = data[0].trim();
                    String idbunga = data[1].trim();
                    String namapelanggan = data[2].trim();
                    String tanggalStr = data[3].trim();
                    int jumlah = Integer.parseInt(data[4].trim());
                    int totalharga = Integer.parseInt(data[5].trim());

                    java.sql.Date tanggal;
                    try {
                        tanggal = java.sql.Date.valueOf(tanggalStr);
                    } catch (Exception e) {
                        System.out.println("Format tanggal salah pada baris: " + baris);
                        continue;
                    }

                    Tokobunga_1 bunga = em.find(Tokobunga_1.class, idbunga);
                    if (bunga == null) {
                        System.out.println("Bunga ID " + idbunga + " tidak ditemukan, dilewati.");
                        continue;
                    }

                    Transaksitokobunga t = new Transaksitokobunga();
                    t.setIdtransaksi(idtransaksi);
                    t.setIdbunga(bunga);
                    t.setNamapelanggan(namapelanggan);
                    t.setTanggal(tanggal);
                    t.setJumlah(jumlah);
                    t.setTotalharga(totalharga);

                    em.persist(t);
                    System.out.println("Input: " + idtransaksi + " - " + namapelanggan);
                }

                em.getTransaction().commit();
                JOptionPane.showMessageDialog(null, "Semua data transaksi berhasil diinput!");

                showTable2();

            } catch (Exception ex) {
                if (em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
                Logger.getLogger(TokoBunga.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
            } finally {
                em.close();
                emf.close();
            }
        }
    }//GEN-LAST:event_BtnUpload2ActionPerformed

    private void BtnCetak2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetak2ActionPerformed
        Connection conn = null;
        Statement stmt;
        PreparedStatement pstmt = null;

        String driver = "org.postgresql.Driver";
        String koneksi = "jdbc:postgresql://localhost:5432/DB_PBO_P4";
        String user = "postgres";
        String password = "1234";

        JasperReport reports;
        String path = ".\\src\\TokoBunga\\ReportDataTransaksi.jasper";
        try {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);
            } catch (SQLException ex) {
                Logger.getLogger(TokoBunga.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                System.getLogger(TokoBunga.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TokoBunga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnCetak2ActionPerformed

    private void BtnDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelete2ActionPerformed
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu dari tabel!");
            return;
        }

        String idTransaksi = jTable2.getValueAt(row, 0).toString();
        String idBunga = jTable2.getValueAt(row, 1).toString();
        String namaPelanggan = jTable2.getValueAt(row, 2).toString();
        String tanggalStr = jTable2.getValueAt(row, 3).toString();
        String jumlahPesananStr = jTable2.getValueAt(row, 4).toString();
        String totalHargaStr = jTable2.getValueAt(row, 5).toString();

        java.util.Date tanggal = null;
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH);
            tanggal = sdf.parse(tanggalStr);
        } catch (Exception e) {
            e.printStackTrace();
        }

        int jumlahPesanan = 0;
        int totalHarga = 0;
        try {
            jumlahPesanan = Integer.parseInt(jumlahPesananStr);
            totalHarga = Integer.parseInt(totalHargaStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format angka tidak valid!");
            return;
        }

        DeleteDialog2 dialog = new DeleteDialog2(new java.awt.Frame(), true, idTransaksi, idBunga, namaPelanggan, tanggal, jumlahPesanan, totalHarga);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        showTable2();
    }//GEN-LAST:event_BtnDelete2ActionPerformed

    private void BtnInsert2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsert2ActionPerformed
        InsertDialog2 dialog = new InsertDialog2(new java.awt.Frame(), true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        showTable2();
    }//GEN-LAST:event_BtnInsert2ActionPerformed

    private void BtnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate2ActionPerformed
        int row = jTable2.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu dari tabel!");
            return;
        }

        SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy", Locale.ENGLISH);
        Date tanggal = null;
        try {
            String tanggalStr = jTable2.getValueAt(row, 3) != null ? jTable2.getValueAt(row, 3).toString() : "";
            if (!tanggalStr.isEmpty()) {
                tanggal = sdf.parse(tanggalStr);
            }
        } catch (ParseException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Format tanggal tidak valid: " + e.getMessage());
            return;
        }

        String idTransaksiLama = jTable2.getValueAt(row, 0).toString();
        String idBunga = jTable2.getValueAt(row, 1).toString();
        String namaPelanggan = jTable2.getValueAt(row, 2).toString();

        int jumlahPesanan;
        int totalHarga;
        try {
            jumlahPesanan = Integer.parseInt(jTable2.getValueAt(row, 4).toString());
            totalHarga = Integer.parseInt(jTable2.getValueAt(row, 5).toString());
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this, "Nilai jumlah atau total harga tidak valid.");
            return;
        }

        java.awt.Frame parentFrame = null;
        java.awt.Window w = SwingUtilities.getWindowAncestor(this);
        if (w instanceof java.awt.Frame) {
            parentFrame = (java.awt.Frame) w;
        }

        UpdateDialog2 dialog = new UpdateDialog2(parentFrame != null ? parentFrame : new java.awt.Frame(),
                true, idTransaksiLama, idBunga, namaPelanggan, tanggal, jumlahPesanan, totalHarga);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        showTable2();
    }//GEN-LAST:event_BtnUpdate2ActionPerformed

    private void BtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetakActionPerformed
        Connection conn = null;
        Statement stmt;
        PreparedStatement pstmt = null;

        String driver = "org.postgresql.Driver";
        String koneksi = "jdbc:postgresql://localhost:5432/DB_PBO_P4";
        String user = "postgres";
        String password = "1234";

        JasperReport reports;
        String path = ".\\src\\TokoBunga\\ReportDataBunga.jasper";
        try {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);
            } catch (SQLException ex) {
                Logger.getLogger(TokoBunga.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                System.getLogger(TokoBunga.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            reports = (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jprint = JasperFillManager.fillReport(path, null, conn);
            JasperViewer jviewer = new JasperViewer(jprint, false);
            jviewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            jviewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(TokoBunga.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BtnCetakActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu dari tabel!");
            return;
        }

        idBungaLama = jTable1.getValueAt(row, 0).toString();
        namaBungaLama = jTable1.getValueAt(row, 1).toString();
        kategoriBungaLama = jTable1.getValueAt(row, 2).toString();
        deskripsiLama = jTable1.getValueAt(row, 3).toString();
        hargaLama = jTable1.getValueAt(row, 4).toString();
        stokLama = jTable1.getValueAt(row, 5).toString();
        ukuranLama = jTable1.getValueAt(row, 6).toString();

        UpdateDialog dialog = new UpdateDialog(this, true, idBungaLama, namaBungaLama, kategoriBungaLama,
                deskripsiLama, hargaLama, stokLama, ukuranLama);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        showTable1();
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInsertActionPerformed
        InsertDialog dialog = new InsertDialog(new java.awt.Frame(), true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        showTable1();
    }//GEN-LAST:event_BtnInsertActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        int row = jTable1.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data dulu dari tabel!");
            return;
        }

        String idBungaLama = jTable1.getValueAt(row, 0).toString();
        String namaBungaLama = jTable1.getValueAt(row, 1).toString();
        String kategoriBungaLama = jTable1.getValueAt(row, 2).toString();
        String deskripsiLama = jTable1.getValueAt(row, 3).toString();
        String hargaLama = jTable1.getValueAt(row, 4).toString();
        String stokLama = jTable1.getValueAt(row, 5).toString();
        String ukuranLama = jTable1.getValueAt(row, 6).toString();

        DeleteDialog dialog = new DeleteDialog(new java.awt.Frame(), true, idBungaLama, namaBungaLama, kategoriBungaLama, deskripsiLama, hargaLama, stokLama, ukuranLama);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        showTable1();
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUploadActionPerformed
        JFileChooser jfc = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
        int returnValue = jfc.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File filePilihan = jfc.getSelectedFile();
            System.out.println("yang dipilih : " + filePilihan.getAbsolutePath());

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PertemuanKesebelasPU");
            EntityManager em = emf.createEntityManager();

            try (BufferedReader br = new BufferedReader(new FileReader(filePilihan))) {
                String baris;
                String pemisah = ";";
                while ((baris = br.readLine()) != null) {
                    if (baris.trim().isEmpty()) {
                        continue;
                    }

                    String[] data = baris.split(pemisah);

                    if (data.length < 7) {
                        System.out.println("Baris tidak lengkap, dilewati: " + baris);
                        continue;
                    }

                    String idbunga = data[0].trim();
                    String namabunga = data[1].trim();
                    String kategoribunga = data[2].trim();
                    String deskripsiproduk = data[3].trim();
                    int harga = Integer.parseInt(data[4].trim());
                    int stok = Integer.parseInt(data[5].trim());
                    String ukuran = data[6].trim();

                    if (!idbunga.isEmpty() && !namabunga.isEmpty() && !kategoribunga.isEmpty()
                            && !deskripsiproduk.isEmpty() && !ukuran.isEmpty()) {
                        em.getTransaction().begin();

                        Tokobunga_1 tb = new Tokobunga_1();
                        tb.setIdbunga(idbunga);
                        tb.setNamabunga(namabunga);
                        tb.setKategoribunga(kategoribunga);
                        tb.setDeskripsiproduk(deskripsiproduk);
                        tb.setHarga(harga);
                        tb.setStok(stok);
                        tb.setUkuran(ukuran);

                        em.persist(tb);
                        em.getTransaction().commit();

                        System.out.println("Berhasil input: " + idbunga + " - " + namabunga);
                    } else {
                        System.out.println("Data tidak valid (ada kolom kosong): " + baris);
                    }
                }

                JOptionPane.showMessageDialog(null, "Semua data dari file berhasil diinput!");
                showTable1();

            } catch (Exception ex) {
                if (em.getTransaction().isActive()) {
                    em.getTransaction().rollback();
                }
                Logger.getLogger(TokoBunga.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + ex.getMessage());
            } finally {
                if (em.isOpen()) {
                    em.close();
                }
                if (emf.isOpen()) {
                    emf.close();
                }
            }
        }
    }//GEN-LAST:event_BtnUploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoBunga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoBunga().setVisible(true);
            }
        });
    }
    DefaultTableModel tbmk;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCetak;
    private javax.swing.JButton BtnCetak2;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnDelete2;
    private javax.swing.JButton BtnExit;
    private javax.swing.JButton BtnInsert;
    private javax.swing.JButton BtnInsert2;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JButton BtnUpdate2;
    private javax.swing.JButton BtnUpload;
    private javax.swing.JButton BtnUpload2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
