/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package TokoBunga;

import TokoBunga.Transaksitokobunga;
import java.text.*;
import java.util.*;
import javax.persistence.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Huawei
 */
public class UpdateDialog2 extends java.awt.Dialog {

    private EntityManagerFactory emf;
    private EntityManager em;

    String idTransaksiLama, idBungaLama, namaPelangganLama;
    Date tanggalLama;
    int jumlahLama, totalHargaLama;

    public void connect() {
        try {
            emf = Persistence.createEntityManagerFactory("PertemuanKesebelasPU");
            em = emf.createEntityManager();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi gagal: " + e.getMessage());
        }
    }

    public UpdateDialog2(java.awt.Frame parent, boolean modal,
            String idTransaksi, String idBunga, String namaPelanggan,
            Date tanggal, int jumlah, int totalHarga) {
        super(parent, modal);
        initComponents();
        connect();

        this.idTransaksiLama = idTransaksi;
        this.idBungaLama = idBunga;
        this.namaPelangganLama = namaPelanggan;
        this.tanggalLama = tanggal;
        this.jumlahLama = jumlah;
        this.totalHargaLama = totalHarga;

        TxtIdTransaksi.setText(idTransaksi);
        TxtIdBunga.setText(idBunga);
        TxtNamaPelanggan.setText(namaPelanggan);
        DtcTanggalTransaksi.setDate(tanggal);
        SpJumlahPesanan.setValue(jumlah);
        TxtTotalHarga.setText(String.valueOf(totalHarga));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnUpdate2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        TxtIdTransaksi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtIdBunga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TxtNamaPelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DtcTanggalTransaksi = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        SpJumlahPesanan = new com.toedter.components.JSpinField();
        jLabel7 = new javax.swing.JLabel();
        TxtTotalHarga = new javax.swing.JTextField();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnUpdate2.setBackground(new java.awt.Color(255, 102, 204));
        BtnUpdate2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        BtnUpdate2.setForeground(new java.awt.Color(255, 255, 255));
        BtnUpdate2.setText("Update");
        BtnUpdate2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdate2ActionPerformed(evt);
            }
        });
        jPanel1.add(BtnUpdate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 100, 30));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("ID Transaksi");
        jLabel2.setAutoscrolls(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 87, -1));

        TxtIdTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdTransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(TxtIdTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 110, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("ID Bunga");
        jLabel3.setAutoscrolls(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        TxtIdBunga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdBungaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtIdBunga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 110, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("Nama Pelanggan");
        jLabel4.setAutoscrolls(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        TxtNamaPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNamaPelangganActionPerformed(evt);
            }
        });
        jPanel1.add(TxtNamaPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 110, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("Tanggal Transaksi");
        jLabel5.setAutoscrolls(true);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel1.add(DtcTanggalTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 110, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Jumlah Pesanan");
        jLabel6.setAutoscrolls(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, -1));
        jPanel1.add(SpJumlahPesanan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 110, -1));

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("Total Harga");
        jLabel7.setAutoscrolls(true);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 90, -1));

        TxtTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTotalHargaActionPerformed(evt);
            }
        });
        jPanel1.add(TxtTotalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void BtnUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdate2ActionPerformed
        int jumlah = (Integer) SpJumlahPesanan.getValue();

        if (TxtIdTransaksi.getText().equals("")
                || TxtIdBunga.getText().equals("")
                || TxtNamaPelanggan.getText().equals("")
                || DtcTanggalTransaksi.getDate() == null
                || jumlah == 0
                || TxtTotalHarga.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Isi semua data!");
            return;
        }

        try {
            String idTransaksiBaru = TxtIdTransaksi.getText();
            String idBungaBaru = TxtIdBunga.getText();
            String namaPelangganBaru = TxtNamaPelanggan.getText();
            Date tanggalBaru = DtcTanggalTransaksi.getDate();
            int jumlahBaru = jumlah;
            int totalHargaBaru = Integer.parseInt(TxtTotalHarga.getText());

            em.getTransaction().begin();

            if (!idTransaksiBaru.equals(idTransaksiLama)) {
                JOptionPane.showMessageDialog(this, "ID Transaksi tidak boleh diubah!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                TxtIdTransaksi.setText(idTransaksiLama);
                em.getTransaction().rollback();
                return;
            }

            Transaksitokobunga trx = em.find(Transaksitokobunga.class, idTransaksiLama);
            if (trx == null) {
                JOptionPane.showMessageDialog(this, "Transaksi tidak ditemukan!");
                em.getTransaction().rollback();
                return;
            }

            Tokobunga_1 bunga = em.find(Tokobunga_1.class, idBungaBaru);
            if (bunga == null) {
                JOptionPane.showMessageDialog(this, "ID Bunga tidak ditemukan!", "Error", JOptionPane.ERROR_MESSAGE);
                em.getTransaction().rollback();
                return;
            }

            trx.setIdbunga(bunga);
            trx.setNamapelanggan(namaPelangganBaru);
            trx.setTanggal(tanggalBaru);
            trx.setJumlah(jumlahBaru);
            trx.setTotalharga(totalHargaBaru);

            em.merge(trx);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(this, "Data transaksi berhasil diperbarui!");
            dispose();

        } catch (Exception e) {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_BtnUpdate2ActionPerformed

    private void TxtIdTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdTransaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdTransaksiActionPerformed

    private void TxtIdBungaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdBungaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdBungaActionPerformed

    private void TxtNamaPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNamaPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNamaPelangganActionPerformed

    private void TxtTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTotalHargaActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                UpdateDialog2 dialog = new UpdateDialog2(new java.awt.Frame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnUpdate2;
    private com.toedter.calendar.JDateChooser DtcTanggalTransaksi;
    private com.toedter.components.JSpinField SpJumlahPesanan;
    private javax.swing.JTextField TxtIdBunga;
    private javax.swing.JTextField TxtIdTransaksi;
    private javax.swing.JTextField TxtNamaPelanggan;
    private javax.swing.JTextField TxtTotalHarga;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
